// Artigos (trials) — 4º lote: Lípides e Osteometabolismo.
// Mesmo formato dos lotes anteriores.
//
// ⚠️ Conteúdo para REVISÃO do professor antes de liberar (entra como rascunho).
// ⚠️ Números escritos de MEMÓRIA (decisão do professor em 2026-07-28: pode
//    escrever primeiro e conferir depois). Enquanto não passarem por PDF, estes
//    artigos são "coerentes internamente, PENDENTES DE REVISÃO" — não conferidos.
'use strict';

const art = (o) => Object.assign({ tipo: 'artigo', privado: true, titulo: '', rascunho: true }, o);

const LIPIDES4 = [

  art({
    sub: 'Lípides', tema: '4S (1994)', fonte: 'Lancet', ano: '1994',
    url: 'https://doi.org/10.1016/S0140-6736(94)90566-5',
    pts: [
      '**Pergunta / população** — Em pacientes **com doença coronariana estabelecida** (n=4.444; angina ou infarto prévio, colesterol total 212–309 mg/dL), baixar o colesterol reduz **mortalidade**?',
      '**Intervenção vs comparador** — **Sinvastatina 20–40 mg/dia** vs **placebo**. Mediana de **5,4 anos**.',
      '**Desfecho primário** — **Morte por qualquer causa** — e é isso que torna o 4S diferente de tudo que veio antes.',
      '**Resultado-chave** — **8,2% vs 11,5% — RR 0,70** (IC95% 0,58–0,85; p=0,0003). Morte coronariana **−42%**. Eventos coronarianos maiores **−34%**. Revascularização **−37%**.',
      '**Segurança** — Sem excesso de câncer nem de morte não cardiovascular — exatamente o medo que travava a área até então.',
      '💡 **O que muda na prática** — É o estudo que **encerrou a dúvida sobre baixar colesterol** e inaugurou a era das estatinas. Antes dele, havia receio real de que reduzir colesterol aumentasse mortalidade não cardiovascular.'
    ],
    resumo: '## Contexto: a suspeita de que baixar colesterol aumentava a mortalidade\nAté 1994 a relação entre colesterol e doença coronariana estava estabelecida, mas o **tratamento** não. Estudos anteriores com fibratos, resinas e dieta reduziam eventos coronarianos e, ao mesmo tempo, mostravam **aumento de mortes não cardiovasculares** — câncer, violência, suicídio. A leitura dominante era que baixar colesterol trocava uma morte por outra. Metanálises da época chegaram a sugerir que o benefício líquido era nulo.\n\nO 4S foi desenhado com **mortalidade total como desfecho primário** justamente para responder a isso. Não era uma escolha estatística confortável — exige amostra e tempo —, mas era a única pergunta que importava.\n\n## Desenho\n- **4.444 pacientes** com **angina ou infarto do miocárdio prévio**, colesterol total entre **212 e 309 mg/dL** após dieta.\n- **Sinvastatina 20 mg/dia**, titulada a **40 mg** se o alvo de colesterol não fosse atingido, vs **placebo**.\n- Mediana de seguimento de **5,4 anos**.\n- Idade 35–70 anos; **19% mulheres**.\n\n## Resultados\n| Desfecho | Sinvastatina | Placebo | Efeito |\n|---|---|---|---|\n| **Morte por qualquer causa** | **8,2%** | 11,5% | **RR 0,70** (0,58–0,85); p=0,0003 |\n| Morte coronariana | — | — | **−42%** |\n| Eventos coronarianos maiores | 19,4% | 28,0% | **−34%** |\n| Revascularização | — | — | **−37%** |\n\n- Redução de **colesterol total ~25%** e de **LDL ~35%**; HDL subiu ~8%.\n- **Não houve** aumento de mortes não cardiovasculares — o achado que desarmou a objeção da época.\n\n## O que o 4S estabeleceu, em uma frase\nBaixar LDL com estatina em quem **já tem** doença coronariana **salva vidas**, e não apenas evita eventos. Toda a prevenção secundária moderna descende daqui.\n\n## Limitações\n- **Prevenção secundária** e colesterol elevado: não responde sobre quem tem LDL normal (isso viria com o JUPITER) nem sobre prevenção primária.\n- **Apenas 19% de mulheres** e faixa etária até 70 anos — a extrapolação para idosos e para mulheres veio depois.\n- Alvo terapêutico da época era o **colesterol total**, não o LDL; a lógica de "quanto mais baixo, melhor" ainda não existia.\n\n## O que muda na prática\n- Em **doença coronariana estabelecida**, estatina não é opcional nem negociável — é o tratamento com prova de mortalidade.\n- Serve para a conversa com o paciente que resiste: o benefício aqui não é um número de laboratório, é **sobreviver**.\n- Historicamente, é a resposta definitiva ao medo de que baixar colesterol fizesse mal por outras vias.'
  }),

  art({
    sub: 'Lípides', tema: 'JUPITER (2008)', fonte: 'NEJM', ano: '2008',
    url: 'https://doi.org/10.1056/NEJMoa0807646',
    pts: [
      '**Pergunta / população** — Em pessoas **sem hiperlipidemia** (n=17.802; **LDL <130 mg/dL**) mas com **PCR ultrassensível ≥2,0 mg/L**, a estatina previne eventos?',
      '**Intervenção vs comparador** — **Rosuvastatina 20 mg/dia** vs **placebo**. Previsto para 5 anos, **interrompido em ~1,9 ano** por benefício.',
      '**Desfecho primário** — Composto de IAM, AVC, revascularização, internação por angina instável ou morte cardiovascular.',
      '**Resultado-chave** — **HR 0,56** (IC95% 0,46–0,69; p<0,00001) — redução de **44%**. LDL caiu **50%** (108 → 55 mg/dL) e a PCR, **37%**. **Mortalidade total: HR 0,80.**',
      '**Segurança** — **Diabetes de início recente mais frequente** (3,0% vs 2,4%; p=0,01) — o primeiro sinal robusto desse efeito de classe.',
      '💡 **O que muda na prática** — Ampliou a indicação para quem tem **LDL normal mas risco inflamatório**, e trouxe à tona o **risco de diabetes** das estatinas — que não anula o benefício, mas entra na conversa.'
    ],
    resumo: '## A hipótese testada\nAs estatinas estavam consagradas em quem tinha **colesterol alto**. Mas metade dos infartos acontece em quem tem LDL considerado normal. O JUPITER testou uma hipótese diferente: e se o alvo não fosse o colesterol, e sim a **inflamação**?\n\n## Desenho\n- **17.802 adultos aparentemente saudáveis** — homens ≥50 e mulheres ≥60 anos —, **sem doença cardiovascular** e **sem hiperlipidemia**: **LDL <130 mg/dL**.\n- Critério de entrada: **PCR ultrassensível ≥2,0 mg/L**.\n- **Rosuvastatina 20 mg/dia** vs **placebo**.\n- Previsto para até 5 anos; **interrompido precocemente com mediana de ~1,9 ano** pelo comitê de segurança, por benefício claro.\n\n## Resultados\n- **Desfecho primário: HR 0,56** (IC95% 0,46–0,69) — **redução de 44%**.\n- **IAM: −54%**; **AVC: −48%**; **revascularização: −46%**.\n- **Morte por qualquer causa: HR 0,80** (0,67–0,97).\n- **LDL: 108 → 55 mg/dL** (−50%). **PCR: −37%.**\n\n## Segurança — o achado que mudou a bula\n**Diabetes de início recente: 3,0% vs 2,4%** (p=0,01). Foi o primeiro sinal robusto, em ensaio grande, do que hoje é reconhecido como **efeito de classe** das estatinas. A leitura correta: o risco é **real, pequeno e concentrado em quem já tem pré-diabetes** — e a redução de eventos cardiovasculares supera com folga esse risco. Mas o dado precisa ser dito ao paciente, não escondido.\n\nSem excesso de miopatia grave ou rabdomiólise. Houve pequeno aumento de HbA1c.\n\n## Limitações\n- **Interrupção precoce superestima o efeito** — é um viés conhecido de ensaios parados por benefício, e aqui o seguimento mediano ficou em menos de 2 anos.\n- **Não separa** o que veio da queda do LDL do que veio da queda da PCR: o estudo não tem braço que reduza só um dos dois. A "hipótese inflamatória" ficou plausível, **não provada** — isso só viria com o CANTOS.\n- População selecionada por PCR: não se aplica a quem tem LDL baixo **e** PCR normal.\n- **Custo-efetividade** discutível em prevenção primária de baixo risco absoluto.\n\n## O que muda na prática\n- Legitimou usar **risco global**, e não só o LDL, para indicar estatina em prevenção primária.\n- Deu número para a conversa sobre **diabetes induzido por estatina**: existe, é pequeno, e não justifica suspender em quem tem indicação cardiovascular.\n- A PCR ultrassensível como critério de seleção **não pegou** na prática de rotina — mas o princípio (tratar risco, não número isolado) ficou.'
  }),

  art({
    sub: 'Lípides', tema: 'IMPROVE-IT (2015)', fonte: 'NEJM', ano: '2015',
    url: 'https://doi.org/10.1056/NEJMoa1410489',
    pts: [
      '**Pergunta / população** — Após **síndrome coronariana aguda** (n=18.144; LDL 50–125 mg/dL em uso de estatina), acrescentar um fármaco **não estatínico** traz benefício adicional?',
      '**Intervenção vs comparador** — **Ezetimiba 10 mg + sinvastatina 40 mg** vs **sinvastatina 40 mg**. Mediana de **6 anos**.',
      '**Desfecho primário** — Composto de morte cardiovascular, evento coronariano maior ou AVC.',
      '**Resultado-chave** — **32,7% vs 34,7% — HR 0,936** (IC95% 0,89–0,99; p=0,016). **LDL 53,7 vs 69,5 mg/dL.** O ganho é **modesto**, mas o significado é grande.',
      '**Segurança** — **Sem sinal novo**: sem excesso de miopatia, hepatotoxicidade ou câncer. A ezetimiba é bem tolerada.',
      '💡 **O que muda na prática** — Primeira prova de que **o benefício vem do LDL baixo em si**, não de um efeito pleiotrópico da estatina. Legitimou a estratégia de **somar fármacos** para atingir a meta.'
    ],
    resumo: '## A pergunta conceitual por trás do estudo\nDurante anos existiu a dúvida: o benefício das estatinas vem de **baixar o LDL** ou de efeitos próprios da molécula — anti-inflamatórios, sobre a placa, sobre o endotélio (os chamados *pleiotrópicos*)? A questão tinha consequência direta: se o benefício fosse pleiotrópico, somar um fármaco **não estatínico** não adiantaria nada.\n\nO IMPROVE-IT foi desenhado para resolver isso. A ezetimiba baixa LDL por um mecanismo **completamente diferente** — inibe a absorção intestinal de colesterol (transportador NPC1L1) — e não tem os efeitos pleiotrópicos atribuídos às estatinas.\n\n## Desenho\n- **18.144 pacientes** estabilizados após **síndrome coronariana aguda**, com **LDL entre 50 e 125 mg/dL** já em tratamento.\n- **Ezetimiba 10 mg + sinvastatina 40 mg** vs **sinvastatina 40 mg + placebo**.\n- Mediana de seguimento de **6 anos** — um dos mais longos da área.\n\n## Resultados\n| | Ezetimiba + sinva | Sinvastatina |\n|---|---|---|\n| **LDL alcançado (1 ano)** | **53,7 mg/dL** | 69,5 mg/dL |\n| **Desfecho primário (7 anos)** | **32,7%** | 34,7% |\n\n- **HR 0,936** (IC95% 0,89–0,99); **p=0,016**. Redução relativa de **6,4%**; redução absoluta de **2 pontos percentuais**.\n- **IAM: −13%**; **AVC isquêmico: −21%**.\n- **Mortalidade total: sem diferença.**\n\n## Como interpretar a magnitude do efeito\nUm HR de 0,936 é **pequeno**. Mas o estudo não foi feito para entregar um efeito grande: a diferença de LDL entre os braços foi de apenas **~16 mg/dL**. O que o IMPROVE-IT prova é a **proporcionalidade**: a magnitude do benefício foi exatamente a esperada pela relação já conhecida entre queda de LDL e redução de eventos (cerca de 20% de redução para cada 39 mg/dL). \n\nOu seja: **o LDL é o alvo, e a via para baixá-lo não importa**. Esse resultado é o alicerce lógico dos inibidores de PCSK9 e do "lower is better".\n\n## Limitações\n- **Diferença pequena de LDL** entre os braços — o estudo tem baixo poder para desfechos individuais.\n- Ganhou significância por pouco (p=0,016) e após 7 anos; um seguimento mais curto teria sido negativo.\n- **Pós-SCA**: não testa ezetimiba em prevenção primária.\n\n## O que muda na prática\n- **Quem não atinge a meta com estatina na dose máxima tolerada tem em quê se apoiar** para somar ezetimiba — barata, oral, bem tolerada.\n- Reforça a meta por **valor de LDL**, não por dose de estatina.\n- É o argumento contra a ideia de que "só estatina funciona".'
  }),

  art({
    sub: 'Lípides', tema: 'FOURIER (2017)', fonte: 'NEJM', ano: '2017',
    url: 'https://doi.org/10.1056/NEJMoa1615664',
    pts: [
      '**Pergunta / população** — Em **doença cardiovascular aterosclerótica estabelecida** (n=27.564; LDL ≥70 mg/dL em estatina otimizada), baixar o LDL a valores **muito baixos** com anti-PCSK9 reduz eventos?',
      '**Intervenção vs comparador** — **Evolocumabe** SC (140 mg a cada 2 semanas ou 420 mg/mês) vs **placebo**, sobre estatina. Mediana de **2,2 anos**.',
      '**Desfecho primário** — Composto de morte cardiovascular, IAM, AVC, internação por angina instável ou revascularização.',
      '**Resultado-chave** — **9,8% vs 11,3% — HR 0,85** (IC95% 0,79–0,92; p<0,001). **LDL 92 → 30 mg/dL (−59%).** Mais da metade chegou a **LDL <25 mg/dL**.',
      '**Segurança** — Nenhum sinal novo, mesmo com LDL extremamente baixo: sem excesso de disfunção cognitiva, catarata, diabetes ou miopatia. Reações no local da injeção.',
      '💡 **O que muda na prática** — Mostra que **não existe piso conhecido de LDL** para segurança. Mas **não reduziu mortalidade cardiovascular**, e o seguimento curto (2,2 anos) é a explicação mais provável.'
    ],
    resumo: '## O que este estudo foi testar\nO IMPROVE-IT havia mostrado que **o LDL é o alvo**. Faltava saber até onde. Os inibidores de **PCSK9** — anticorpos monoclonais que impedem a degradação do receptor de LDL — permitiram, pela primeira vez, levar o LDL a valores que nenhum fármaco oral alcança.\n\n## Desenho\n- **27.564 pacientes** com **doença cardiovascular aterosclerótica** (infarto prévio, AVC não hemorrágico ou doença arterial periférica sintomática) e **LDL ≥70 mg/dL** apesar de estatina de intensidade moderada a alta.\n- **Evolocumabe** SC, 140 mg quinzenal ou 420 mg mensal, vs **placebo**.\n- Mediana de **2,2 anos**.\n\n## Resultados\n- **LDL: 92 → 30 mg/dL** — redução de **59%**. **Mais de metade dos pacientes atingiu LDL <25 mg/dL.**\n- **Desfecho primário: 9,8% vs 11,3% — HR 0,85** (0,79–0,92); p<0,001.\n- **Desfecho secundário-chave** (morte CV, IAM ou AVC): **HR 0,80**.\n- **IAM: −27%**; **AVC: −21%**; **revascularização: −22%**.\n\n## ⚠️ Os dois pontos que geram discussão\n**1. Não houve redução de morte cardiovascular** (HR 1,05) nem de mortalidade total. A explicação mais aceita é a **duração**: 2,2 anos é pouco para o benefício de mortalidade aparecer — no 4S, a curva de mortalidade só se separou depois de ~2 anos, e ali o efeito era muito maior. Mas é honesto dizer que **o estudo não demonstrou benefício de mortalidade**, e não que ele existe e não foi visto.\n\n**2. LDL de 30 mg/dL é seguro?** Era a grande apreensão — o colesterol é substrato de membranas, hormônios esteroides e mielina. O FOURIER, e a análise específica dos que chegaram a **<20 mg/dL**, **não mostraram** excesso de disfunção cognitiva, catarata, hemorragia cerebral, diabetes de início recente ou disfunção hormonal. É a melhor evidência disponível de que **não há piso conhecido**.\n\n## Limitações\n- **Seguimento curto (2,2 anos)** para um desfecho que depende de anos de exposição.\n- **Custo** — é a barreira prática real, e é o que mantém o anti-PCSK9 como fármaco de 3ª linha na maioria dos protocolos.\n- Efeito absoluto modesto: **1,5 ponto percentual** em 2,2 anos.\n\n## O que muda na prática\n- Em **doença aterosclerótica de muito alto risco que não atinge a meta** com estatina + ezetimiba, o anti-PCSK9 tem prova de redução de eventos.\n- Tira do caminho o medo de **LDL muito baixo**.\n- A decisão passa a ser de **custo e acesso**, não de eficácia ou de segurança.'
  }),

  art({
    sub: 'Lípides', tema: 'ODYSSEY OUTCOMES (2018)', fonte: 'NEJM', ano: '2018',
    url: 'https://doi.org/10.1056/NEJMoa1801174',
    pts: [
      '**Pergunta / população** — Após **síndrome coronariana aguda recente** (n=18.924; 1 a 12 meses do evento, LDL ≥70 mg/dL em estatina de alta intensidade), o anti-PCSK9 reduz eventos?',
      '**Intervenção vs comparador** — **Alirocumabe** SC 75–150 mg a cada 2 semanas, **titulado para manter LDL entre 25 e 50 mg/dL**, vs **placebo**. Mediana de **2,8 anos**.',
      '**Desfecho primário** — Composto de morte coronariana, IAM não fatal, AVC isquêmico ou angina instável com internação.',
      '**Resultado-chave** — **9,5% vs 11,1% — HR 0,85** (IC95% 0,78–0,93; p<0,001). **Morte por qualquer causa: HR 0,85** (0,73–0,98) — o achado que o FOURIER não teve.',
      '**Segurança** — Só reações no local da injeção em excesso. Sem sinal com LDL muito baixo.',
      '💡 **O que muda na prática** — É o irmão do FOURIER com **seguimento maior e população de maior risco** — e por isso o benefício de mortalidade apareceu. O ganho concentra-se em quem tinha **LDL basal ≥100 mg/dL**.'
    ],
    resumo: '## Como ler junto com o FOURIER\nOs dois estudos testam a mesma classe e chegam ao **mesmo HR de 0,85** no desfecho primário. A diferença está em duas escolhas de desenho, e é nelas que está o interesse:\n\n- **População de risco mais alto e mais agudo**: síndrome coronariana **de 1 a 12 meses**, quando o risco de novo evento é máximo. O FOURIER incluiu doença estável, muitas vezes anos após o evento.\n- **Seguimento maior**: **2,8 anos** contra 2,2.\n\nEssas duas diferenças bastaram para que a **mortalidade total** se tornasse significativa aqui e não lá.\n\n## Desenho\n- **18.924 pacientes** de 1 a 12 meses após SCA, com **LDL ≥70 mg/dL**, não-HDL ≥100 ou apoB ≥80, já em **estatina de alta intensidade** (ou dose máxima tolerada).\n- **Alirocumabe** SC quinzenal, com **titulação para manter o LDL entre 25 e 50 mg/dL** — um desenho incomum e inteligente: em vez de dose fixa, mira uma **faixa**, e reduz a dose (ou passa a placebo cego) se o LDL cair abaixo de 15 mg/dL.\n- Mediana de **2,8 anos**.\n\n## Resultados\n- **Desfecho primário: 9,5% vs 11,1% — HR 0,85** (0,78–0,93); p<0,001.\n- **Morte por qualquer causa: HR 0,85** (0,73–0,98) — nominalmente significativa.\n- **LDL: 87 → ~40 mg/dL** ao longo do estudo.\n\n## O achado que orienta a seleção do paciente\nO benefício **não foi homogêneo**. No subgrupo com **LDL basal ≥100 mg/dL**, a redução absoluta foi bem maior, e foi ali que se concentrou o sinal de mortalidade. Em quem já entrava com LDL próximo de 70, o ganho absoluto foi pequeno.\n\nA leitura prática: **o anti-PCSK9 rende mais em quem está mais longe da meta**, não em quem já está perto dela. É o mesmo princípio de sempre — o benefício absoluto acompanha o risco basal e a magnitude da queda de LDL.\n\n## Limitações\n- Mortalidade total foi **desfecho hierarquizado** e a significância é **nominal** — não é o desfecho primário, e merece a ressalva.\n- O desenho com titulação por faixa dificulta comparar dose com o FOURIER.\n- Custo, de novo, é a barreira prática.\n\n## O que muda na prática\n- **Pós-SCA com LDL persistentemente alto apesar de estatina de alta intensidade** é a melhor indicação que a classe tem.\n- Reforça iniciar cedo, quando o risco de recorrência é maior.\n- Dá o argumento que faltava sobre mortalidade — com a ressalva de que é achado secundário.'
  }),

  art({
    sub: 'Lípides', tema: 'REDUCE-IT (2019)', fonte: 'NEJM', ano: '2019',
    url: 'https://doi.org/10.1056/NEJMoa1812792',
    pts: [
      '**Pergunta / população** — Em pacientes **em estatina, com LDL controlado mas triglicerídeos 135–499 mg/dL** (n=8.179; com doença cardiovascular ou diabetes + fator de risco), o icosapento de etila reduz eventos?',
      '**Intervenção vs comparador** — **Icosapento de etila 4 g/dia** (EPA puro, esterificado) vs **placebo de óleo mineral**. Mediana de **4,9 anos**.',
      '**Desfecho primário** — Composto de morte cardiovascular, IAM, AVC, revascularização ou angina instável.',
      '**Resultado-chave** — **17,2% vs 22,0% — HR 0,75** (IC95% 0,68–0,83; p<0,001). Redução absoluta de **4,8 pontos percentuais** — grande para a área.',
      '**Segurança** — ⚠️ **Fibrilação atrial** mais frequente (5,3% vs 3,9%) e **sangramento** maior (2,7% vs 2,1%).',
      '💡 **O que muda na prática** — É o único ômega-3 com prova de desfecho, e a redução absoluta de 4,8 pontos percentuais é grande para a área. **Mas a controvérsia do placebo de óleo mineral é séria** e precisa ser dita.'
    ],
    resumo: '## Contexto: os ensaios anteriores com ômega-3 foram negativos\nDoses baixas de EPA+DHA não reduziram eventos em nenhum ensaio grande. O REDUCE-IT mudou três variáveis de uma vez: **dose alta (4 g)**, **EPA puro** (sem DHA) e **população selecionada por triglicerídeos elevados** com LDL já controlado.\n\n## Desenho\n- **8.179 pacientes** em estatina, com **LDL entre 41 e 100 mg/dL** (controlado) e **triglicerídeos entre 135 e 499 mg/dL**.\n- **71% em prevenção secundária** (doença cardiovascular estabelecida); o restante com **diabetes + pelo menos um fator de risco**.\n- **Icosapento de etila 4 g/dia** vs **placebo**. Mediana de **4,9 anos**.\n\n## Resultados\n- **Desfecho primário: 17,2% vs 22,0% — HR 0,75** (0,68–0,83); p<0,001.\n- **Redução absoluta de 4,8 pontos percentuais** — magnitude incomum para um fármaco somado a estatina otimizada.\n- **Morte cardiovascular: HR 0,80**. **IAM: −31%.** **AVC: −28%.**\n- Triglicerídeos caíram cerca de **18%**.\n\n## ⚠️ A controvérsia do comparador\nO comparador foi **óleo mineral**, e no braço placebo houve **aumento de LDL (~10%) e de PCR (~30%)** ao longo do estudo. Isso levanta a hipótese de que parte do benefício observado venha de o **placebo ter piorado** o perfil, e não só de o fármaco ter melhorado.\n\nOs argumentos dos dois lados:\n- **A favor do fármaco:** a magnitude do efeito é grande demais para ser explicada só por uma piora de 10% no LDL do placebo; e o benefício **não se correlacionou** com a queda de triglicerídeos, sugerindo mecanismo próprio do EPA (estabilização de membrana, efeito antiarrítmico e anti-inflamatório).\n- **Contra:** o STRENGTH, que testou carboxilas de ômega-3 com **placebo de óleo de milho**, foi **negativo** — é o contraponto mais forte à hipótese de efeito próprio do EPA.\n\nA posição defensável hoje: o efeito é **provavelmente real, mas de magnitude incerta**.\n\n## Segurança\n- **Fibrilação atrial: 5,3% vs 3,9%** — clinicamente relevante e frequentemente esquecido.\n- **Sangramento: 2,7% vs 2,1%** — atenção em quem usa anticoagulante ou dupla antiagregação.\n\n## O que muda na prática\n- Faz sentido em **prevenção secundária com triglicerídeos persistentemente elevados apesar de estatina** — não como hipolipemiante genérico.\n- **Não** extrapolar para outros ômega-3: a dose, a formulação (EPA puro) e a população importam. Cápsula de óleo de peixe de farmácia **não é** icosapento de etila.\n- Perguntar sobre **palpitações e sangramento** no seguimento.'
  })

];

const OSTEO4 = [

  art({
    sub: 'Osteometabolismo', tema: 'FIT (1996)', fonte: 'Lancet', ano: '1996',
    url: 'https://doi.org/10.1016/S0140-6736(96)90911-1',
    pts: [
      '**Pergunta / população** — Em mulheres na pós-menopausa **com fratura vertebral prévia** (n=2.027; DMO de colo femoral baixa), o alendronato previne novas fraturas?',
      '**Intervenção vs comparador** — **Alendronato** 5 mg/dia (elevado a 10 mg) vs **placebo**, com cálcio e vitamina D nos dois braços. **3 anos**.',
      '**Desfecho primário** — **Nova fratura vertebral** radiográfica.',
      '**Resultado-chave** — **8,0% vs 15,0% — RR 0,53** (redução de 47%). **Fratura de quadril: RR 0,49.** Qualquer fratura clínica: **−28%**.',
      '**Segurança** — Sem excesso de eventos gastrointestinais graves em relação ao placebo neste estudo.',
      '💡 **O que muda na prática** — É o ensaio que estabeleceu o **bisfosfonato como tratamento de primeira linha** na osteoporose com fratura prévia, com redução de fratura de quadril — o desfecho que realmente importa.'
    ],
    resumo: '## Por que a fratura de quadril é o desfecho que conta\nDensitometria é um marcador; fratura é a doença. E entre as fraturas, a **de quadril** é a que carrega mortalidade em torno de 20% no primeiro ano e perda definitiva de autonomia. Um tratamento de osteoporose só se justifica se mexer nisso.\n\nO braço do FIT com **fratura vertebral prévia** — o de maior risco basal — foi desenhado para ter poder justamente aí.\n\n## Desenho\n- **2.027 mulheres** na pós-menopausa, 55–81 anos, com **pelo menos uma fratura vertebral prévia** e DMO de colo femoral baixa.\n- **Alendronato 5 mg/dia** nos 2 primeiros anos, elevado a **10 mg/dia** no 3º, vs **placebo**.\n- **Cálcio e vitamina D** oferecidos aos dois braços — detalhe que evita atribuir ao fármaco o que é reposição.\n- **3 anos**.\n\n## Resultados\n| Desfecho em 3 anos | Alendronato | Placebo | Efeito |\n|---|---|---|---|\n| **Nova fratura vertebral** | **8,0%** | 15,0% | **RR 0,53** |\n| **Fratura de quadril** | 1,1% | 2,2% | **RR 0,49** |\n| Fratura de punho | — | — | RR 0,52 |\n| Qualquer fratura clínica | 13,6% | 18,2% | **−28%** |\n\n- Ganho de DMO: **~6,2% na coluna** e **~4,1% no colo femoral**.\n- O efeito sobre fratura vertebral já era detectável **no primeiro ano**.\n\n## O que o FIT estabeleceu\nQue **antirreabsortivo previne fratura**, incluindo a de quadril, em quem tem alto risco basal. Toda a estrutura atual — tratar quem já fraturou, sem depender de um valor de T-escore — vem daqui.\n\n## Limitações\n- **Mulheres na pós-menopausa com fratura prévia**: risco basal alto. O braço paralelo do FIT, **sem fratura prévia**, mostrou benefício em fratura clínica apenas no subgrupo com **T-escore ≤ −2,5** — dado que sustenta o limiar de tratamento usado até hoje.\n- **3 anos**: não informa sobre uso prolongado, fratura atípica ou osteonecrose de mandíbula, que só apareceriam com a experiência pós-comercialização.\n- Não inclui homens.\n\n## O que muda na prática\n- **Fratura vertebral prévia = tratar**, independentemente do valor da densitometria. É o cenário de maior benefício absoluto.\n- Cálcio e vitamina D são **base**, não tratamento — o comparador do FIT já os recebia.\n- O efeito aparece **cedo**, o que ajuda na adesão de quem quer saber "quando vou ver resultado".'
  }),

  art({
    sub: 'Osteometabolismo', tema: 'HORIZON-PFT (2007)', fonte: 'NEJM', ano: '2007',
    url: 'https://doi.org/10.1056/NEJMoa067312',
    pts: [
      '**Pergunta / população** — Em mulheres na pós-menopausa com osteoporose (n=3.889), uma infusão **anual** de zoledronato previne fraturas?',
      '**Intervenção vs comparador** — **Ácido zoledrônico 5 mg IV uma vez ao ano** (3 infusões) vs **placebo**. **3 anos**.',
      '**Desfecho primário** — **Nova fratura vertebral morfométrica** e **fratura de quadril**.',
      '**Resultado-chave** — **Fratura vertebral: 3,3% vs 10,9% — redução de 70%.** **Fratura de quadril: 1,4% vs 2,5% — redução de 41%.** Não vertebral: −25%.',
      '**Segurança** — **Reação de fase aguda** (febre, mialgia, artralgia) em ~32% após a 1ª infusão. **Fibrilação atrial grave mais frequente** (1,3% vs 0,5%) — achado nunca plenamente explicado.',
      '💡 **O que muda na prática** — Resolve o problema número um do bisfosfonato oral: **adesão**. Uma infusão por ano substitui 365 comprimidos em jejum.'
    ],
    resumo: '## O problema que a via intravenosa resolve\nO alendronato funciona — o FIT provou. Mas exige comprimido em jejum, com água, de pé, esperando 30 minutos. Na vida real, **metade das pacientes abandona em um ano**, e osteoporose não tratada não dói: não há sintoma que lembre de tomar. O zoledronato anual troca esse problema por uma consulta.\n\n## Desenho\n- **3.889 mulheres** na pós-menopausa com osteoporose (T-escore ≤ −2,5 no colo femoral, ou ≤ −1,5 com duas fraturas vertebrais).\n- **Ácido zoledrônico 5 mg IV**, infusão de 15 minutos, **uma vez ao ano**, por 3 anos — total de **3 infusões**.\n- **Cálcio e vitamina D** em ambos os braços.\n\n## Resultados\n| Desfecho em 3 anos | Zoledronato | Placebo | Redução |\n|---|---|---|---|\n| **Nova fratura vertebral** | **3,3%** | 10,9% | **−70%** |\n| **Fratura de quadril** | **1,4%** | 2,5% | **−41%** |\n| Fratura não vertebral | 8,0% | 10,7% | **−25%** |\n| Qualquer fratura clínica | 8,4% | 12,8% | **−33%** |\n\n- Ganho de DMO: **~6,7% na coluna** e **~5,1% no colo femoral** em 3 anos.\n\n## Segurança — dois pontos que mudam a conversa pré-infusão\n**1. Reação de fase aguda.** Febre, mialgia, artralgia e cefaleia nas 72 horas seguintes, em cerca de **32% após a primeira infusão** — e bem menos nas seguintes (~7% e ~3%). É autolimitada e responde a paracetamol. **Avisar antes é o que evita a paciente achar que teve uma reação grave e recusar a segunda dose.**\n\n**2. ⚠️ Fibrilação atrial como evento adverso grave: 1,3% vs 0,5%** (p<0,001). O achado surpreendeu, nunca foi bem explicado mecanisticamente e **não se confirmou de forma consistente** em outros estudos com bisfosfonato. Fica como sinal a considerar em quem já tem cardiopatia atrial.\n\nSem excesso de osteonecrose de mandíbula neste estudo (dois casos, um em cada braço).\n\n## Limitações\n- **3 anos** — a extensão (HORIZON-PFT Extension) sugeriu que continuar até 6 anos traz ganho adicional modesto, sustentando a discussão de **feriado terapêutico**.\n- Só mulheres na pós-menopausa.\n- Exige **função renal preservada** (contraindicado com clearance abaixo de ~35 mL/min) e correção prévia de **hipocalcemia e deficiência de vitamina D**.\n\n## O que muda na prática\n- **Primeira escolha quando a adesão é o problema** — e ela quase sempre é.\n- Também quando há intolerância ou contraindicação gastrointestinal ao oral, ou após fratura de quadril.\n- **Antes de infundir:** conferir clearance, cálcio e vitamina D, e avisar da reação de fase aguda.'
  }),

  art({
    sub: 'Osteometabolismo', tema: 'FREEDOM (2009)', fonte: 'NEJM', ano: '2009',
    url: 'https://doi.org/10.1056/NEJMoa0809493',
    pts: [
      '**Pergunta / população** — Em mulheres na pós-menopausa com osteoporose (n=7.868; T-escore entre −2,5 e −4,0), o denosumabe previne fraturas?',
      '**Intervenção vs comparador** — **Denosumabe 60 mg SC a cada 6 meses** vs **placebo**. **3 anos**.',
      '**Desfecho primário** — **Nova fratura vertebral** em 3 anos.',
      '**Resultado-chave** — **2,3% vs 7,2% — redução de 68%.** **Fratura de quadril: −40%.** Não vertebral: **−20%**.',
      '**Segurança** — Perfil semelhante ao placebo no estudo. ⚠️ O problema real veio depois: **suspender causa reganho acelerado de reabsorção e risco de fraturas vertebrais múltiplas**.',
      '💡 **O que muda na prática** — Aplicação semestral, **sem restrição renal** como os bisfosfonatos — mas **não pode ser simplesmente interrompido**. Quem inicia denosumabe assume um compromisso de continuidade ou de transição planejada.'
    ],
    resumo: '## O mecanismo, que explica tanto a virtude quanto o defeito\nO denosumabe é um **anticorpo monoclonal anti-RANKL**. Ele bloqueia o sinal que recruta e ativa osteoclastos — e o faz de forma **potente e completamente reversível**. Não se incorpora ao osso, ao contrário dos bisfosfonatos.\n\nEssa reversibilidade determina o perfil clínico do fármaco: dá um efeito antirreabsortivo profundo enquanto se usa, e **um rebote quando se para**.\n\n## Desenho\n- **7.868 mulheres** na pós-menopausa, 60–90 anos, com **T-escore entre −2,5 e −4,0** em coluna ou colo femoral.\n- **Denosumabe 60 mg por via subcutânea a cada 6 meses** vs **placebo**, por **3 anos**.\n- Cálcio e vitamina D em ambos os braços.\n\n## Resultados\n| Desfecho em 3 anos | Denosumabe | Placebo | Redução |\n|---|---|---|---|\n| **Nova fratura vertebral** | **2,3%** | 7,2% | **−68%** |\n| **Fratura de quadril** | 0,7% | 1,2% | **−40%** |\n| Fratura não vertebral | 6,5% | 8,0% | **−20%** |\n\n- Ganho de DMO: **~9,2% na coluna** e **~6,0% no quadril total** em 3 anos — e, diferentemente dos bisfosfonatos, o ganho **continua subindo** ano após ano na extensão de 10 anos.\n\n## ⚠️ O que o FREEDOM não mostrou, e que define o uso hoje\nO estudo de 3 anos é tranquilizador. **O problema apareceu depois**, na fase de extensão e na prática: **suspender o denosumabe provoca um rebote de reabsorção óssea**, com perda rápida de toda a DMO ganha e — o que é grave — **fraturas vertebrais múltiplas** em algumas pacientes, às vezes em quem nunca havia fraturado.\n\nO mecanismo é coerente com a farmacologia: sem incorporação ao osso, quando o anticorpo desaparece o RANKL volta de uma vez, com hiperativação osteoclástica.\n\n**Consequência prática, que precisa ser dita à paciente na primeira consulta:** denosumabe **não se interrompe simplesmente**. Ou se mantém, ou se faz **transição planejada para um bisfosfonato** ao suspender. E **atraso na dose importa** — a janela de 6 meses não é sugestão.\n\n## Limitações\n- **3 anos** para o desfecho principal; o que se sabe de longo prazo vem da extensão aberta, sem comparador.\n- Só mulheres na pós-menopausa.\n- Osteonecrose de mandíbula e fratura atípica de fêmur são raras, mas descritas com uso prolongado.\n\n## O que muda na prática\n- **Boa opção quando há disfunção renal** — não tem a restrição de clearance dos bisfosfonatos (embora exija atenção redobrada à **hipocalcemia** nesse cenário).\n- Aplicação semestral favorece adesão, e o ganho de DMO é o maior entre os antirreabsortivos.\n- **O compromisso de continuidade é parte da prescrição.** Iniciar sem combinar isso é preparar uma complicação evitável.'
  }),

  art({
    sub: 'Osteometabolismo', tema: 'Teriparatida — Neer (2001)', fonte: 'NEJM', ano: '2001',
    url: 'https://doi.org/10.1056/NEJM200105103441904',
    pts: [
      '**Pergunta / população** — Em mulheres na pós-menopausa **com fratura vertebral prévia** (n=1.637), um agente **anabólico** previne novas fraturas?',
      '**Intervenção vs comparador** — **Teriparatida (PTH 1-34) 20 ou 40 µg SC/dia** vs **placebo**. Mediana de **21 meses** — o estudo foi **interrompido precocemente** por achado de osteossarcoma em ratos.',
      '**Desfecho primário** — **Nova fratura vertebral**.',
      '**Resultado-chave** — Com 20 µg: **5% vs 14% — redução de 65%**. **Fratura não vertebral: −53%.** Ganho de DMO na coluna de **~9%**.',
      '**Segurança** — Náusea, cefaleia, cãibras, **hipercalcemia transitória**. O sinal de **osteossarcoma em roedores** não se confirmou em humanos ao longo de duas décadas de uso.',
      '💡 **O que muda na prática** — É o primeiro **anabólico**: forma osso novo em vez de apenas frear a perda. Reservado para osteoporose **grave** ou falha de antirreabsortivo — e a sequência importa: **anabólico primeiro, antirreabsortivo depois**.'
    ],
    resumo: '## Exposição contínua vs. intermitente ao PTH\nPTH cronicamente elevado — como no hiperparatireoidismo — **destrói** osso. Mas o mesmo hormônio, dado em **pulsos diários curtos**, faz o oposto: estimula preferencialmente o osteoblasto e **forma** osso novo. É a diferença entre exposição contínua e intermitente, e é toda a base da teriparatida.\n\nAté 2001, todo tratamento de osteoporose era **antirreabsortivo**: freava a perda. Nenhum reconstruía.\n\n## Desenho\n- **1.637 mulheres** na pós-menopausa **com pelo menos uma fratura vertebral prévia**.\n- **Teriparatida 20 µg ou 40 µg SC/dia** vs **placebo**, com cálcio e vitamina D.\n- Previsto para 3 anos; **interrompido com mediana de 21 meses** quando surgiu o achado de **osteossarcoma em ratos** submetidos a doses altas por quase toda a vida.\n\n## Resultados (dose de 20 µg, a que ficou em uso)\n| Desfecho | Teriparatida 20 µg | Placebo | Redução |\n|---|---|---|---|\n| **Nova fratura vertebral** | **5%** | 14% | **−65%** |\n| Fratura vertebral moderada/grave | — | — | **−90%** |\n| **Fratura não vertebral por fragilidade** | 3% | 6% | **−53%** |\n\n- **DMO da coluna: +9,7%**; colo femoral: **+2,8%**.\n- A dose de 40 µg **não foi melhor** em fratura e teve mais efeitos adversos — por isso a aprovada foi a de 20 µg. É um bom exemplo de que mais dose não é mais benefício.\n\n## O alarme do osteossarcoma, e o que se sabe hoje\nRatos expostos a doses muito altas por praticamente toda a vida desenvolveram osteossarcoma — o que interrompeu o estudo e gerou um alerta em bula, além do limite de **24 meses** de uso. Depois de **mais de duas décadas** de uso clínico e de vigilância ativa, **não se confirmou** excesso de osteossarcoma em humanos, e a restrição vem sendo relativizada. O modelo do roedor — osso que cresce continuamente — não representa bem o humano.\n\n## A sequência importa\nUm ponto que os estudos posteriores deixaram claro e que é fácil errar: **anabólico depois de antirreabsortivo rende menos** (o osso está com remodelação suprimida). E, ao terminar a teriparatida, **é obrigatório emendar um antirreabsortivo** — sem isso, o osso formado se perde.\n\n**A ordem correta é: anabólico primeiro, antirreabsortivo depois.**\n\n## Limitações\n- **Interrompido precocemente** (21 meses) — não informa sobre 3 anos completos.\n- Aplicação **diária subcutânea** e custo alto limitam o uso.\n- Contraindicado em doença metabólica óssea de alto turnover, hiperparatireoidismo, radioterapia óssea prévia e hipercalcemia.\n\n## O que muda na prática\n- Reservado para **osteoporose grave**: múltiplas fraturas, T-escore muito baixo, ou **falha do antirreabsortivo**.\n- **Planejar a sequência desde o início**, não no fim do tratamento.\n- Monitorar cálcio; a hipercalcemia costuma ser leve e transitória.'
  }),

  art({
    sub: 'Osteometabolismo', tema: 'ARCH (2017)', fonte: 'NEJM', ano: '2017',
    url: 'https://doi.org/10.1056/NEJMoa1708322',
    pts: [
      '**Pergunta / população** — Em mulheres na pós-menopausa com **osteoporose grave e fratura prévia** (n=4.093), o romosozumabe seguido de alendronato é superior ao alendronato isolado?',
      '**Intervenção vs comparador** — **Romosozumabe 210 mg SC/mês por 12 meses**, seguido de alendronato, vs **alendronato desde o início**. Total de **24 meses**.',
      '**Desfecho primário** — Nova fratura vertebral em 24 meses e fratura clínica.',
      '**Resultado-chave** — **Fratura vertebral: 6,2% vs 11,9% — redução de 48%.** **Fratura de quadril: −38%.** Não vertebral: **−19%**.',
      '**Segurança** — ⚠️ **Excesso de eventos cardiovasculares graves no 1º ano: 2,5% vs 1,9%** (IAM, AVC e morte CV). É o achado que define a indicação.',
      '💡 **O que muda na prática** — O tratamento mais eficaz disponível para osteoporose grave, com um **duplo mecanismo** (forma osso e freia reabsorção) — mas **contraindicado em quem teve IAM ou AVC no último ano**.'
    ],
    resumo: '## Um mecanismo que não existia antes\nO romosozumabe é um **anticorpo monoclonal antiesclerostina**. A esclerostina, produzida pelo osteócito, **freia** a formação óssea; bloqueá-la libera o osteoblasto. O resultado é incomum e é o que torna o fármaco singular: ele **forma osso e, ao mesmo tempo, reduz a reabsorção** — desacopla as duas coisas, que normalmente andam juntas.\n\nO efeito é potente, mas **transitório**: dura cerca de 12 meses, o que define a duração do tratamento.\n\n## Desenho\n- **4.093 mulheres** na pós-menopausa com **osteoporose e fratura por fragilidade prévia** — população de risco alto, mais grave que a do FREEDOM ou do HORIZON.\n- **Romosozumabe 210 mg SC mensal por 12 meses → alendronato** vs **alendronato do início ao fim**.\n- Total de **24 meses**. Note que o comparador é **ativo**, não placebo — o que torna o resultado mais exigente.\n\n## Resultados\n| Desfecho em 24 meses | Romo → alendronato | Alendronato | Redução |\n|---|---|---|---|\n| **Nova fratura vertebral** | **6,2%** | 11,9% | **−48%** |\n| **Fratura de quadril** | 2,0% | 3,2% | **−38%** |\n| Fratura não vertebral | 8,7% | 10,6% | **−19%** |\n| Fratura clínica | 9,7% | 13,0% | **−27%** |\n\nSuperar o alendronato — que já é tratamento eficaz — nessas magnitudes é o que coloca o romosozumabe no topo em eficácia.\n\n## ⚠️ O sinal cardiovascular, que é a informação decisiva\nNo **primeiro ano** — o período com romosozumabe — houve **excesso de eventos cardiovasculares graves: 2,5% vs 1,9%**, incluindo infarto, AVC e morte cardiovascular.\n\nO que se sabe e o que não se sabe:\n- O sinal **não apareceu** no FRAME, que comparou romosozumabe com **placebo**. Isso levantou a hipótese de que parte da diferença viesse de um **efeito protetor do alendronato**, e não de dano do romosozumabe — mas é hipótese, não explicação estabelecida.\n- O mecanismo é plausível nos dois sentidos: a esclerostina é expressa no endotélio e na aorta, e seu bloqueio pode ter efeito vascular.\n\nA consequência regulatória foi direta: **contraindicado em quem teve infarto ou AVC no último ano**, e uso com cautela em quem tem risco cardiovascular alto. Na prática, **a avaliação cardiovascular passa a fazer parte da prescrição de um fármaco ósseo** — o que não é intuitivo.\n\n## Limitações\n- **Duração de 12 meses** para o romosozumabe: não é tratamento contínuo.\n- **Exige sequência com antirreabsortivo** — sem isso o ganho se perde, como na teriparatida.\n- Só mulheres na pós-menopausa; custo alto.\n\n## O que muda na prática\n- **Osteoporose grave com fratura, alto risco iminente**, é onde ele rende mais — sobretudo em quem já falhou com antirreabsortivo.\n- **Perguntar sobre infarto e AVC no último ano antes de prescrever.** É a pergunta que muda a conduta.\n- Planejar desde o início a **transição para bisfosfonato ou denosumabe** ao fim dos 12 meses.'
  })

];

module.exports = { LIPIDES4, OSTEO4, TODOS4: LIPIDES4.concat(OSTEO4) };
